---
- name: Restart realmd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: realmd
    state: restarted

- name: Clear sssd cache
  become: true
  ansible.builtin.shell: sss_cache -E 2>/dev/null
  register: sss_cache_clean
  failed_when: sss_cache_clean.rc not in [ 0, 2 ]

- name: Restart sssd
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: sssd
    state: restarted
